---
title: "Stat 110: Fundamentals of statistics"
author: Fall 2017 
---

### [Office Hours](Schedule.html)

### Announcements


### Resources

* [JMP installation instructions](https://silasbergen.github.io/JMP_installation.html)
* [Tinkerplots installation instructions](https://silasbergen.github.io/Tinkerplots.pdf)
* [Tutoring services](http://www.winona.edu/tutoring/)


### Extra credit

* 


### Notes

 * Lecture 1: Introduction to data | [PPT](https://www.dropbox.com/s/sv1s4tq879y97ua/1%20-%20Introduction%20to%20data.pptx?dl=0) | [PDF](https://www.dropbox.com/s/qwwjiwlqlj7tvkz/1%20-%20Introduction%20to%20data.pdf?dl=0) 
 * Lecture 2: Summarizing a single variable | [PPT](https://www.dropbox.com/s/mztaipz6jo2w7ut/2%20-%20Summarizing%20a%20single%20variable.pptx?dl=0) | [PDF](https://www.dropbox.com/s/b3wwwk14937ce3p/2%20-%20Summarizing%20a%20single%20variable.pdf?dl=0)
 * Lecture 3: associations between variables, confounding, and study design | [PPT](https://www.dropbox.com/s/xs0nkkgsr42lb6h/3%20-%20Associations%20between%20variables.pptx?dl=0) | [PDF](https://www.dropbox.com/s/142aeehcbe3v7ww/3%20-%20Associations%20between%20variables.pdf?dl=0) | [Part 1 video](https://mediaspace.mnscu.edu/media/Stat+110A+F17A+Lecture+3+part+1/0_871iwtrh) | [Part 2 video](https://mediaspace.mnscu.edu/media/Stat+110A+F17A+Lecture+3+part+2/0_atx7myar)
 * Lecture 4: populations; parameters; samples; statistics | [PPT](https://www.dropbox.com/s/1269wlc08kprnl1/4%20-%20Populations%20and%20samples.pptx?dl=0) | [PDF](https://www.dropbox.com/s/fyzd1ca0y252m1h/4%20-%20Populations%20and%20samples.pdf?dl=0) |  [Video recording](https://mediaspace.mnscu.edu/media/Stat+110A+F17A+Lecture+4+-+populations%2C+parameters%2C+samples%2C+statistics/0_sb2ljx7v) 
* Lecture 5: Introduction to inference | [PPT](https://www.dropbox.com/s/y1e505xyomw7l4i/5%20-%20Intro%20to%20Inference.pptx?dl=0) | [PDF](https://www.dropbox.com/s/bs3j1u8pxty8j6o/5%20-%20Intro%20to%20Inference.pdf?dl=0) | [Video recording](https://mediaspace.mnscu.edu/media/Stat+110-F17A+Lecture+5/0_vghw2h1k)
* Lecture 6: Hypothesis testing | [PPT](https://www.dropbox.com/s/jfjg5tvefrm6pgw/6%20-%20Hypothesis%20testing.pptx?dl=0) | [PDF](https://www.dropbox.com/s/befmg5n3mf0hx96/6%20-%20Hypothesis%20testing.pdf?dl=0) | [Video recording](https://mediaspace.mnscu.edu/media/Stat+110A+F17+-+Lecture+6/0_tusygxeh)

### Homework

* [Homework 1 (Due 8/29)](https://www.dropbox.com/s/oaa5y8q9odhm79y/HW1.docx?dl=0) | [Key](https://www.dropbox.com/s/buefxdy4m3yh391/HW1-KEY.docx?dl=0)
* [Homework 2 (Due 9/10)](https://www.dropbox.com/s/a6ip4yl4dji64xk/HW2.docx?dl=0) | [KEY](https://www.dropbox.com/s/oc2ry6ov5ftqu8w/HW2-KEY.docx?dl=0)
* [Homework 3](https://www.dropbox.com/s/2qu6ps0ni1qxhyk/HW3.docx?dl=0) | [KEY](https://www.dropbox.com/s/8zq0ctcvx3pqsec/HW3-KEY.docx?dl=0)


### Practice problems

* [Lecture 3 FEV practice problem](https://www.dropbox.com/s/id0t3svswof1y3j/FEV-Confounding.docx?dl=0)
* [Lecture 5 intro to inference practice problems](https://www.dropbox.com/s/1qekwneomvsp5yw/Simulations-wormhole-swain-alabama.docx?dl=0)
* [Lecture 6 Hypothesis testing practice problem](https://www.dropbox.com/s/bc63xrg4apc7t0n/Hypothesis%20testing.docx?dl=0)

### Data


-   [Birth weight
    data](https://github.com/silasbergen/CourseResources/raw/master/Data/Birthweight.jmp)
-   [BRFSS
    data](https://www.dropbox.com/s/lbqr85a1to664n9/BRFSS.jmp?dl=0)
-   [California expenditures data](https://www.dropbox.com/s/x22xv6aljppse5b/CA_Expenditures.jmp?dl=0)
-   [FEV
    data](https://github.com/silasbergen/CourseResources/raw/master/Data/FEVdata.jmp)
-   [HIV
    data](https://github.com/silasbergen/CourseResources/raw/master/Data/HIV-Antiretroviral.jmp)
-   [Iraq War
    data](https://github.com/silasbergen/CourseResources/raw/master/Data/IraqWar.jmp)
-   [Lions
    data](https://github.com/silasbergen/CourseResources/raw/master/Data/Lions.jmp)
-   [Lymphedenopathy
    data](https://github.com/silasbergen/CourseResources/raw/master/Data/LymphNodes.jmp)
-   [Pancreatic cancer
    data](https://github.com/silasbergen/CourseResources/raw/master/Data/Pancreatic_Cancer_Data.jmp)
-   [Pew research
    data](https://github.com/silasbergen/CourseResources/raw/master/Data/PewFacebookData.jmp)
-   [Smiles
    data](https://github.com/silasbergen/CourseResources/raw/master/Data/Smiles.jmp)
-   [Student Survey
    Data (Fall 2017)](https://www.dropbox.com/s/aqd6cvhs2ebagz0/StudentSurveyFall2017.jmp?dl=0)
-   [Subaru
    data](https://github.com/silasbergen/CourseResources/raw/master/Data/subarus.jmp)
-   [Titanic
    data](https://github.com/silasbergen/CourseResources/raw/master/Data/Titanic.jmp)
-   [Trombone
    data](https://github.com/silasbergen/CourseResources/raw/master/Data/trombone.jmp)






